<?php
return [
	'salesStartTime' => '2017-08-01 00:00:00',
	'salesEndTime' => '2017-09-09 23:59:59',
	'salesItems' => 'all',//['1001', '1002', '1009'],//
	'items' => [
		'1026' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1026.png',
			'name' => 'ムム第二形態の印欠片',
			'desc' => 'ムム第二形態の印欠片を 100 個集めることでムム第二形態の印を合成できます。',
			'point' => 200,
			'salesPoint' => 200,
			'isValid' => 1,
			'id' => 200986,
		],
		'1027' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1027.png',
			'name' => 'ムム第三形態の印欠片',
			'desc' => 'ムム第三形態の印欠片を 100 個集めることでムム第三形態の印を合成できます。',
			'point' => 300,
			'salesPoint' => 300,
			'isValid' => 1,
			'id' => 200987,
		],
		'1004' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1004.png',
			'name' => '精錬石	',
			'desc' => '100 精錬EXPを獲得することができます',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 41000,
		],
		'1005' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1005.png',
			'name' => '進化石	',
			'desc' => '馬術のレベルアップに必要なアイテム',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 60530,
		],
		'1006' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1006.png',
			'name' => '祝福石	',
			'desc' => '進階に必要なアイテム',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 60500,
		],
		'1023' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1023.png',
			'name' => 'アバター結晶',
			'desc' => 'ジュエリー，アクセサリーの加工と合成に必要なアイテム',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 60630,
		],
		'1007' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1007.png',
			'name' => '英雄更新券',
			'desc' => '英雄ショップ更新に必要なアイテム',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 23100,
		],
		'1001' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1001.png',
			'name' => '奪取回数カード',
			'desc' => '地下探索の奪取回数を増やすアイテム。',
			'point' => 25,
			'salesPoint' => 10,
			'isValid' => 1,
			'id' => 60111,
		],
		'1003' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1003.png',
			'name' => '活力カード',
			'desc' => '地下探索で使える活力を10ポイント回復するアイテム。',
			'point' => 100,
			'salesPoint' => 80,
			'isValid' => 1,
			'id' => 60113,
		],
		'1008' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1008.png',
			'name' => 'ノーマル召喚チケット',
			'desc' => '使用後，召喚を一回行えます',
			'point' => 100,
			'salesPoint' => 80,
			'isValid' => 1,
			'id' => 20100,
		],
		'1009' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1009.png',
			'name' => 'レア召喚チケット',
			'desc' => 'レア召喚1回分',
			'point' => 300,
			'salesPoint' => 240,
			'isValid' => 1,
			'id' => 20200,
		],
		'1002' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1002.png',
			'name' => 'スタミナカード',
			'desc' => 'ダンジョン探索で使えるスタミナを30ポイント回復するアイテム。',
			'point' => 80,
			'salesPoint' => 64,
			'isValid' => 1,
			'id' => 62003,
		],
		'1010' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1010.png',
			'name' => 'Goldナゲット（小）',
			'desc' => '売却で100000Gold獲得できます',
			'point' => 130,
			'salesPoint' => 100,
			'isValid' => 1,
			'id' => 63001,
		],
		'1011' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1011.png',
			'name' => 'EXP宝具（N）',
			'desc' => '200 宝具EXPを獲得することができます',
			'point' => 5,
			'salesPoint' => 4,
			'isValid' => 0,
			'id' => 19000,
		],
		'1012' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1012.png',
			'name' => 'EXP宝具（R）',
			'desc' => '1000 宝具EXPを獲得することができます',
			'point' => 50,
			'salesPoint' => 40,
			'isValid' => 0,
			'id' => 19020,
		],
		'1013' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1013.png',
			'name' => 'EXP宝具（SR）',
			'desc' => '10000 宝具EXPを獲得することができます',
			'point' => 130,
			'salesPoint' => 100,
			'isValid' => 1,
			'id' => 19030,
		],
		'1014' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1014.png',
			'name' => 'SR装備欠片ボックス',
			'desc' => 'ランダムで1～3個のSR装備(欠片)を獲得できます',
			'point' => 50,
			'salesPoint' => 40,
			'isValid' => 0,
			'id' => 80030,
		],
		'1015' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1015.png',
			'name' => 'SSR装備欠片ボックス',
			'desc' => 'ランダムで1～3個のSSR装備(欠片)を獲得できます',
			'point' => 200,
			'salesPoint' => 160,
			'isValid' => 1,
			'id' => 80040,
		],
		'1016' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1016.png',
			'name' => 'ルーン宝箱の鍵（銅）',
			'desc' => 'ルーン宝箱(銅)を開くアイテム',
			'point' => 130,
			'salesPoint' => 100,
			'isValid' => 0,
			'id' => 17500,
		],
		'1017' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1017.png',
			'name' => 'ルーン宝箱の鍵（銀）',
			'desc' => 'ルーン宝箱(銀)を開くアイテム',
			'point' => 300,
			'salesPoint' => 240,
			'isValid' => 1,
			'id' => 17510,
		],
		'1018' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1018.png',
			'name' => 'ルーン宝箱の鍵（金）',
			'desc' => 'ルーン宝箱(金)を開くアイテム',
			'point' => 600,
			'salesPoint' => 480,
			'isValid' => 1,
			'id' => 17520,
		],
		'1019' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1019.png',
			'name' => 'EXPスクロールLv1',
			'desc' => '1000 英雄EXPを獲得できます',
			'point' => 5,
			'salesPoint' => 4,
			'isValid' => 0,
			'id' => 61000,
		],
		'1020' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1020.png',
			'name' => 'EXPスクロールLv2',
			'desc' => '5000 英雄EXPを獲得できます',
			'point' => 15,
			'salesPoint' => 12,
			'isValid' => 1,
			'id' => 61001,
		],
		'1021' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1021.png',
			'name' => 'EXPスクロールLv3',
			'desc' => '20000 英雄EXPを獲得できます',
			'point' => 50,
			'salesPoint' => 40,
			'isValid' => 1,
			'id' => 61002,
		],
		'1022' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1022.png',
			'name' => 'EXPスクロールLv4',
			'desc' => '50000 英雄EXPを獲得できます',
			'point' => 130,
			'salesPoint' => 100,
			'isValid' => 1,
			'id' => 61003,
		],
		'1024' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1024.png',
			'name' => '雷帝のハンマー',
			'desc' => '攻撃型宝具：キャラクターの攻撃力を上昇させる',
			'point' => 2500,
			'salesPoint' => 999,
			'isValid' => 1,
			'id' => 18020,
		]
		,
		'1025' => [
			'picPath' => '//ap-statics.loas.jp/mm2/official/images/pointmall/1025.png',
			'name' => '妖精の鏡',
			'desc' => '防御型宝具，キャラクターの防御力を上昇させる',
			'point' => 2500,
			'salesPoint' => 999,
			'isValid' => 1,
			'id' => 18520,
		]
	]
];